### PR TITLE
Make the "Downloadable Drivers" page usable in low resolutions

### PR DESCRIPTION
**Pull request by mariospr**
As discussed with @twaugh on IRC, I'm proposing a UI change similar to [the one we just integrated downstream in Endless to cope with very low resolutions, on top of s-c-p 1.5.5](https://github.com/endlessm/system-config-printer/pull/10), see if that's something upstream would like to have too.

This pull request makes different adjustments to the "Downloadable Drivers" page of the NewPrinterWindow UI file, so that the end result is that it's usable in very low resolutions.

Besides those changes in that page, it also makes the whole content area of the GtkWindow scrollable, so that it's still usable in cases where all the other measures would not be enough to keep the buttons of the action area on screen (e.g. clicking on the new 'Driver details' GtkExpander).

Last, we also change the default (not minimum) size of the window be a bit bigger than the minimum resolution used when in NTSC composite mode (720x480) so that we make sure to use all the available space for users using that particular configuration, while being just big enough (although this is a bit subjective, of course) for bigger resolutions.

See below a couple of screenshots showcasing the new UI:

**Initial page of the NewPrinterWindow window / 720x480**:
screenshot from 2016-02-02 18-39-26

**"Search for drivers" page / 720x480**:
screenshot from 2016-02-02 18-39-43

**"Downloadable drivers" page / 720x480 / 'Details' collapsed**:
screenshot from 2016-02-02 18-39-49

**"Downloadable drivers" page / 720x480 / 'Details' expanded / Scrolled window at TOP**:
screenshot from 2016-02-02 18-41-27

**"Downloadable drivers" page / 720x480 / 'Details' expanded / Scrolled window at BOTTOM**:
screenshot from 2016-02-02 18-41-41

**"Downloadable drivers" page / 1280x960 / 'Details' collapsed**:
screenshot from 2016-02-02 18-44-25

**"Downloadable drivers" page / 1280x960 / 'Details' expanded (No scroll needed)**:
screenshot from 2016-02-02 18-44-35

Please review and let me know what you think. Thanks!

### CODE REVIEW

**Comment by twaugh** [comment]
cc @jpopelka in case you get a chance to look at this

**Comment by mariospr** [comment]
Just got back here by reviewing my TODO and thought I'd make a ping :-)

**Comment by mariospr** [comment]
Just another ping, now I updated the pull request to set default size to 800x600 instead of 720x480.

Reason for that change is that I recently realized (on Endless) that 720x480 was like way too small for systems with big enough resolutions, where using that small dimensions would lead to having to use scroll bars for no good reason.

So, I played a bit around with different defaults and I settled on 800x600 as a good enough option.

**Comment by mariospr** [comment]
Sorry for insisting, just trying not to let this fall into oblivion :). @jpopelka Any feedback?

**Comment by jpopelka** [comment]
No feedback yet, sorry, but I've been aware of this.

**Comment by mariospr** [comment]
You been aware of it is feedback already :-). The main reason why I insist so much is because I think it's useful (in our case it did make a huge difference) and also because any changes in this UI file upstream will make it very hard to rebase our customization downstream, so I'd rather do some extra work in this pull request to get to a common ground that both upstream and us can use, if possible, than keep applying them over and over again.

Still, I understand this being like top-low priority, so will still pinging. Only think I'd ask is to keep this in mind (and my "offer" to help getting to a middle ground by re-working my patches) if s-c-p ever updates this UI file again, if possible.

Thanks!

**Comment by mariospr** [comment]
Closing because it has been way too long and I don't have now the time nor the dev setup to continue working on this. Feel free to pick it up an open a new PR if needed.

**Comment by tillkamppeter** [comment]
The downloadable drivers are obsolete anyway, at OpenPrinting we are in the middle of the development of the new Printer Applications. No drivers in LSB packages any more (LSB was not supported any more by Debian for several years), but instead, we will soon have printer (and scanner) drivers as so-called Printer Applications in the Snap Store, working with nearly any Linux distribution.
In addition, printer and scanner drivers will only be needed for legacy or specialty devices. Most standard printers nowadays do driverless IPP printing, so they just work with the software which comes with your operating system.
So no worries about the downloadable drivers feature of system-config-printer.
But thanks to everyone who has worked on it, it helped us through several years.

**Pull request closed without merging**
