### PR TITLE
Accessibility improvements

### PR DESCRIPTION
**Pull request by vvillenave**
Greetings everybody,  
I’ve been working on making this program fully usable by visually-impaired users;  
this is what I’m coming up with so far; a big stumbling block remains the troubleshooter,  
but I’m hoping to offer a fix in the future about that.

### CODE REVIEW

**Comment by zdohnal** [comment]
Thank you for the info @vvillenave ! I'll test it once I get into system-config-printer again. Now I'm busy with other responsibilities, sorry :(

**Comment by vvillenave** [comment]
Nice: that Orca bug I mentioned has been fixed in the meantime.   
So now it’s up to you @zdohnal, whenever you find a bit of time :-)

**Comment by vvillenave** [comment]
Greetings @zdohnal, a happy new year to you! Any chance of seeing this PR merged?

**Comment by zdohnal** [comment]
Hi @vvillenave ,

I'm really sorry... I haven't got into testing it so far :( but I have it in my log.

**Comment by zdohnal** [comment]
Hi @vvillenave ,

I'm sorry for long delay, but I was able to reproduce the issue (I heard the incorrect naming by orca) and I verified your PR fixed the issue.

Thank you so much for the patch and patience!

**Pull request merged**
